---
dependency:
  name: galaxy
  options:
    force: False
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .

platforms:
  - name: ${MOLECULE_DISTR:-debian}${MOLECULE_DISTR_VERSION:-10}
    image: moletti/molecule-${MOLECULE_DISTR:-debian}:${MOLECULE_DISTR_VERSION:-10}
    pre_build_image: true
    privileged: true
    groups: ["${MOLECULE_DISTR:-debian}"]
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ~

provisioner:
  name: ansible

verifier:
  name: ansible
