---
name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    if: "!contains(github.event.head_commit.message, '[release]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Release
        uses: moletti/semantic-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
